#!/usr/bin/env bash

#: exec_target = cli

## Execute gulp command
##
## Usage: fin gulp

# Abort if anything fails
set -e

# fix profile
source ~/.profile

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}
gulp ${@:-"build"}
#-------------------------- END: Execution --------------------------------
