#!/usr/bin/env bash

#: exec_target = cli

## Usage: fin console

# Abort if anything fails
set -e

# fix profile
source ~/.profile

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}
php bin/console ${@}
#-------------------------- END: Execution --------------------------------
