#!/usr/bin/env bash

#: exec_target = cli

## Usage: fin gulp

# Abort if anything fails
set -e

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}
gulp ${1:-"build"}
#-------------------------- END: Execution --------------------------------
