#!/usr/bin/env bash

#: exec_target = cli

## Usage: fin npm

# Abort if anything fails
set -e

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}
npm ${1:-"install"}
#-------------------------- END: Execution --------------------------------
