#!/usr/bin/env bash

#: exec_target = cli

## Execute npm command
##
## Usage: fin npm

# Abort if anything fails
set -e

# fix profile
source ~/.profile

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}
npm ${@:-"install"}
#-------------------------- END: Execution --------------------------------
