#!/usr/bin/env bash

## Download and restore database
##
## Usage: fin init-db

# Abort if anything fails
set -e

#-------------------------- Execution --------------------------------
fin download-db
fin restore-db
#-------------------------- END: Execution --------------------------------
