parameters:
  locale: pl
  base_url: example_domain_name
  secret: random_secret_string

  database_driver: pdo_mysql
  # DO NOT CHANGE, DEFAULT DOCKSAL DATABASE CONFIGURATION
  database_host: db
  database_port: 3306
  database_name: default
  database_user: user
  database_password: user
