#!/usr/bin/env bash

## Download uploaded files
##
## Usage: fin download-wp-uploads

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

if [[ "" == "$REMOTE_HOST_URL" ]]; then
    printf "${COLOR_RED}Please define ${COLOR_RED_BG}\$REMOTE_HOST_URL${COLOR_RED} in ${COLOR_RED_BG}.docksal/docksal-local.env${COLOR_RED} file, eg. ${COLOR_RED_BG}\$REMOTE_HOST_URL=http://example.com${COLOR_OFF}\n"
    exit 1
fi

#-------------------------- Execution --------------------------------
cd "$wp_uploads_dump_dir_path" || exit 11
download_file "$REMOTE_HOST_URL/$wp_uploads_dump_secret_name" "$wp_uploads_dump_dir_path/$wp_uploads_dump_file_name"
