#!/usr/bin/env bash

## Share uploaded files
##
## Usage: fin share-wp-uploads

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
cd "$wp_uploads_dump_dir_path" || exit 11
wp_uploads_dump_file_name=$1
if [[ -z "$wp_uploads_dump_file_name" ]]; then
    wp_uploads_dump_file_name=$(
        ls -t ${wp_uploads_dump_file_pattern} | head -1
    )
fi
if [[ -f "$wp_uploads_dump_file_name" ]]; then
    copy_file "$wp_uploads_dump_dir_path/$wp_uploads_dump_file_name" "$web_dir_path/$wp_uploads_dump_secret_name"
else
    printf "There is no dump file under '%s' directory!\n" "$wp_uploads_dump_dir_path"
    printf "Please run 'fin backup-wp-uploads' command to pack uploads to archive file.\n"
    exit 33
fi
