#!/usr/bin/env bash

## Download database from URL
##
## Usage: fin download-db

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

if [[ "" == "$REMOTE_HOST_URL" ]]; then
    printf "${COLOR_RED}Please define ${COLOR_RED_BG}\$REMOTE_HOST_URL${COLOR_RED} in ${COLOR_RED_BG}.docksal/docksal-local.env${COLOR_RED} file, eg. ${COLOR_RED_BG}\$REMOTE_HOST_URL=http://example.com${COLOR_OFF}\n"
    exit 1
fi
if [[ "" == "$REMOTE_RDS_DB_NAME" ]]; then
    printf "${COLOR_RED}Please define ${COLOR_RED_BG}\$REMOTE_RDS_DB_NAME${COLOR_RED} in ${COLOR_RED_BG}.docksal/docksal-local.env${COLOR_RED} file${COLOR_OFF}\n"
    exit 2
fi

#-------------------------- Execution --------------------------------
cd "$db_dump_dir_path" || exit 11
download_file "$REMOTE_HOST_URL/$db_dump_sql_secret_name" "$db_dump_dir_path/$db_dump_sql_file_name"
download_file "$REMOTE_HOST_URL/$db_dump_gzip_secret_name" "$db_dump_dir_path/$db_dump_gzip_file_name"
