#!/usr/bin/env bash

## Download and restore database
##
## Usage: fin migrate-db

# Abort if anything fails
set -e

#-------------------------- Execution --------------------------------
fin backup-db
fin restore-db
#-------------------------- END: Execution --------------------------------
