#!/usr/bin/env bash

## Backup Drupal site
##
## Usage: fin backup-dru-site

# Abort if anything fails
# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
fin drush config:export -y
