#!/usr/bin/env bash

## Backup Drupal content
##
## Usage: fin backup-dru-files

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
cd "$dru_files_dir_path" || exit 11
printf "${COLOR_YELLOW}Backup from ${COLOR_YELLOW_H}%s${COLOR_OFF}${COLOR_YELLOW} to ${COLOR_YELLOW_H}%s${COLOR_OFF}${COLOR_YELLOW} file${COLOR_OFF}\n" "$dru_files_dir_path" "$dru_files_dump_dir_path/$dru_files_dump_file_name"
mkdir -p "$dru_files_dump_dir_path"
zip "$dru_files_dump_dir_path/$dru_files_dump_file_name" *
