#!/usr/bin/env bash

## Restore Drupal site
##
## Usage: fin restore-dru-site

# Abort if anything fails
set -e

cd ${PROJECT_ROOT}
fin db import .docksal/services/db/dump/dump.sql
fin drush config:import -y
