#!/usr/bin/env bash

## Restore Drupal content
##
## Usage: fin restore-dru-files

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
cd "$dru_files_dump_dir_path" || exit 11
dru_files_dump_file_name=$1
if [[ -z "$dru_files_dump_file_name" ]]; then
    dru_files_dump_file_name=$(
        ls -t $dru_files_dump_file_pattern | head -1
    )
fi
if [[ -f "$dru_files_dump_file_name" ]]; then
    unzip $dru_files_dump_dir_path/$dru_files_dump_file_name -d $dru_files_dir_path
else
    printf "There is no dump file under '%s' directory!\n" "$dru_files_dump_dir_path"
    printf "Please run 'fin backup-dru-files' command to pack files to archive file.\n"
    exit 33
fi
