#!/usr/bin/env bash

## Restore Drupal site
##
## Usage: fin restore-dru-site

# Abort if anything fails
# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
fin drush config:import -y
