#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
_confirm "\033[0;41mDo You really want to recreate all project components again?\033[0m"

# Stack initialization
printf "${COLOR_YELLOW_BG} Step 1 ${COLOR_YELLOW} Initializing stack...${COLOR_OFF}\n"
if [[ "${DOCKER_RUNNING}" == "true" ]]; then
    fin reset -f
else
    fin up
fi
if [[ "$(fin config | grep mysql)" ]]; then
    printf "${COLOR_YELLOW}Waiting 10s for MySQL to initialize...${COLOR_OFF}\n"
    sleep 10
fi

# Site initialization
printf "${COLOR_YELLOW_BG} Step 2 ${COLOR_YELLOW} Preparing site...${COLOR_OFF}\n"
# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
fin prepare-site

printf "${COLOR_YELLOW_BG} DONE! ${COLOR_YELLOW}Open ${COLOR_YELLOW_BG}http://${VIRTUAL_HOST}${COLOR_YELLOW} in your browser to verify the setup.\n"

#-------------------------- END: Execution --------------------------------
