#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin prepare-site

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Settings --------------------------------
#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------
function copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f ${dest} ]]; then
		echo "Copying ${dest}..."
		cp ${source} ${dest}
	else
		echo "${dest} already in place."
	fi
}
#-------------------------- END: Helper functions --------------------------------
